### ISSUE TITLE
小bug建议修改

### ISSUE THREAD

**Issue by qinglt** [fengxiaoruia/QL-Emotion-jar#1]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/97783786/195555597-191812f8-d34d-432e-af6d-4eb4b649610d.png">

**Comment by fengxiaoruia** [comment]
已修改
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengxiaoruia/QL-Emotion-jar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 下午5:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fengxiaoruia/QL-Emotion-jar] 小bug建议修改 (Issue #1)

**Comment by qinglt** [comment]
源码可以提供一份吗
